[package]
name = "7kayoh/feather-roblox"
version = "3.0.0"
authors = ["7kayoh <hello@7kayoh.net>"]
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.1.1-beta"